add core file
jztechpe/api.recommendation pull request #1
Opened 2021-12-15 23:14 UTC by Sentra

2021-12-23 15:45 UTC, hansfelix requested changes

2021-12-23 15:45 UTC, hansfelix commented on packages/common/services/recommendation.service.js
> +                const availableProducts = await this._validateProducts(pluginResponse.result);
No debería devolver únicamente un array de ids? Tal cual envía la api de cms

2021-12-23 16:13 UTC, PedroDLC1210 requested changes

2021-12-23 16:13 UTC, PedroDLC1210 commented on packages/common/services/recommendation.service.js
> +            }
por que el get de product?, el front se encarga de hacer el obtencion del producto.

2021-12-23 16:14 UTC, Sentra commented on packages/common/services/recommendation.service.js
> +            }
ahi verificaba si tenia stock para solo devolver los que tenia stock disponible

2021-12-23 16:15 UTC, Sentra commented on packages/common/services/recommendation.service.js
> +            }
pero ya se borro pq esa validacion de stock lo puede manejar la web

2021-12-23 16:20 UTC, PedroDLC1210 requested changes

2021-12-23 16:20 UTC, PedroDLC1210 commented on packages/common/services/recommendation.service.js
> +        };
pon un comentario TODO que es un mock

2021-12-23 16:20 UTC, PedroDLC1210 commented on packages/common/services/recommendation.service.js
> +            const pluginResponse = await pluginEngine.execute(entity.operation, entity);
Revisaste los ejemplos? de payment gateway e integracion?, esto necesita un contexto

2021-12-23 16:20 UTC, PedroDLC1210 commented on packages/common/services/recommendation.service.js
> +            const pluginResponse = await pluginEngine.execute(entity.operation, entity);
https://github.com/jztechpe/integration.inboundreceive/blob/70a6d9ccfbbd2ae9d1264b5f7a5fe204bfb0f8da/processor/common/runner.js#L79

2021-12-24 14:28 UTC, hansfelix approved these changes

2021-12-24 14:49 UTC, PedroDLC1210 approved these changes

2021-12-24 16:31 UTC, merged